# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='architectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.TextField()),
                ('field2', models.TextField()),
                ('field3', models.TextField()),
                ('field4', models.TextField()),
                ('field5', models.TextField()),
                ('field6', models.TextField()),
                ('field7', models.TextField()),
                ('field8', models.TextField()),
                ('field9', models.TextField()),
            ],
        ),
    ]
