# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Table2App', '0003_auto_20170223_1814'),
    ]

    operations = [
	migrations.RenameModel('architectures', 'architecture')
    ]
