# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Table2App', '0004_auto_20170223_1820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='architecture',
            new_name='architectures',
        ),
    ]
